---
title: "Weekly: Total Page Reach by user country. (Unique Users)"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

### Total Likes by Gender and Age {data-commentary-width=560}

```{r, echo = F}

knitr::opts_chunk$set(echo=F, warning=FALSE, message=FALSE)

#pacman::p_install_gh("vosonlab/SocialMediaLab")
pacman::p_load(tidyverse, magrittr, stringr, scales, lubridate, tidytext, tidyr, ggthemes, janitor, Rfacebook, SocialMediaLab, highcharter)
```



```{r}
hc_world_map_motion <- function(data, year = "year", iso3 = "iso3", value = "perc", label = ""){
  ds <- data[,c(year, iso3, value)]
  colnames(ds) <- c("year", "iso3", "value")
  ds <- ds %>%
    #mutate(id = 1:n()) %>%
    #mutate(perc = ifelse(perc < 0.01 & perc > -0.01, 0, perc)) %>%
    group_by(iso3) %>% 
    #split(.$id) # from base R
    do(item = list(
      iso3 = first(.$iso3),
      sequence = .$value,
      value = first(.$value))
    ) %>% 
    .$item
  #ds[[4]]

  high_map <- highcharter::highchart(type = "map") %>% 
    highcharter::hc_add_series(
      data = ds,
      name = label,
      mapData = worldgeojson,
      joinBy = "iso3",
      borderWidth = 0.01
    ) %>% 
    #highcharter::hc_colorAxis(stops = highcharter::color_stops()) %>%  
    #highcharter::hc_colorAxis(stops = stops) %>%
    #  highcharter::hc_legend(layout = "vertical", reversed = TRUE,
    #            floating = TRUE, align = "right") %>% 
    highcharter::hc_add_theme(highcharter::hc_theme_smpl()) %>% 
    highcharter::hc_motion(
      enabled = T,
      axisLabel = "year",
      labels = sort(unique(data$year)),
      series = 0,
      updateIterval = 50,
      magnet = list(
        round = "floor",
        step = 0.01
      )
    ) 
  
  return(high_map)
}
```

```{r}
cntry_daily_reach <- readr::read_csv("data/cntry_daily_reach.csv") %>% janitor::clean_names()

dscrs3 <- as.list(cntry_daily_reach[1,])

cntry_daily_reach %<>% filter(!is.na(date)) 

cntry <- colnames(cntry_daily_reach)[-1] %>% str_extract("..$") %>% 
  countrycode::countrycode("iso2c", "country.name") 

cntry[134] <- "Kosovo"

cntry <- c("date", cntry)

colnames(cntry_daily_reach) <- cntry

cntry_daily_reach %<>% 
  gather("cntry", "reach", -date) %>% 
  mutate(reach = as.numeric(reach))


```



```{r}

weekly <- cntry_daily_reach %>% 
  mutate(wks = lubridate::week(date)) %>% 
  group_by(wks) %>% 
  arrange(date) %>% 
  slice(1) %>% 
  select(date, wks)

cntry_weekly_reach <- cntry_daily_reach %>% 
  mutate(wks = lubridate::week(date)) %>% 
  group_by(wks, cntry) %>% 
  summarise(reach = sum(reach, na.rm = T)) %>% 
  mutate(reach = ifelse(is.nan(reach), NA, reach)) %>% 
  left_join(weekly, by = "wks") %>% 
  mutate(
    iso3 = countrycode::countrycode(
      cntry, 
      origin = "country.name", 
      destination = "iso3c"))



data(worldgeojson, package = "highcharter")

  range01 <- function(x){(x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm = T))}


stops <- data.frame(
  q = 0:8/8,
  #c = viridis::viridis(6, option = "A"),
  c = c("#f7fcf5",
"#e5f5e0",
"#c7e9c0",
"#a1d99b",
    "#74c476",
    "#41ab5d",
"#238b45",
"#006d2c",
"#00441b"),
  stringsAsFactors = FALSE
) %>% highcharter::list_parse2()



cntry_weekly_reach %>% 
  mutate(year = lubridate::as_date(date)) %>% 
#  mutate(reach = ifelse(is.na(reach), 0, reach)) %>% 
  mutate(reach = as.numeric(reach)) %>% 
  arrange(date) %>% 
  hc_world_map_motion(
    year = "year", 
    iso3 = "iso3", 
    value = "reach"
  ) %>%
  highcharter::hc_colorAxis(stops = stops) %>%
  highcharter::hc_title(
    text = "Weekly: Total Page Reach by user country. (Unique Users)"
  ) %>% 
  highcharter::hc_subtitle(text = "Based on Data from Omar Saif Ghobash's Facebook page (October 9th 2017 - January 7th 2018)") %>% highcharter::hc_add_theme(highcharter::hc_theme_smpl())
```

## Without animation

```{r}
hc_world_map <- function(data, iso3 = "iso3", value = "perc", label = ""){
  ds <- data[,c(iso3, value)]
  colnames(ds) <- c("iso3", "value")


  high_map <- highcharter::highchart(type = "map") %>% 
    highcharter::hc_add_series(
      data = ds,
      name = label,
      mapData = worldgeojson,
      joinBy = "iso3",
      borderWidth = 0.01
    ) 
    #highcharter::hc_colorAxis(stops = highcharter::color_stops()) %>%  
    #highcharter::hc_colorAxis(stops = stops) %>%
    #  highcharter::hc_legend(layout = "vertical", reversed = TRUE,
    #            floating = TRUE, align = "right") %>% 
   
  
  return(high_map)
}
```

```{r}

stops <- data.frame(
  q = 0:7/7,
  #c = viridis::viridis(6, option = "A"),
  c = c(#"#f7fcf5",
"#e5f5e0",
"#c7e9c0",
"#a1d99b",
    "#74c476",
    "#41ab5d",
"#238b45",
"#006d2c",
"#00441b"),
  stringsAsFactors = FALSE
) %>% highcharter::list_parse2()

cntry_weekly_reach %>% 
  select(iso3, reach) %>% 
  group_by(iso3) %>% 
  summarize(reach = sum(reach, na.rm = T)) %>% 
  hc_world_map(
    iso3 = "iso3", 
    value = "reach"
  ) %>%
  highcharter::hc_colorAxis(stops = stops) %>%
  highcharter::hc_title(
    text = "Total Page Reach (October 9th 2017 - January 7th 2018)"
  ) %>% 
  highcharter::hc_subtitle(text = "Based on Data from Omar Saif Ghobash's Facebook page. \t By user country in unique users (Total = 264.755)") %>%
#  highcharter::hc_credits(enabled = TRUE, text = "Based on Data from Omar Saif Ghobash's Facebook page") %>% 
  highcharter::hc_add_theme(highcharter::hc_theme_smpl()) %>% 
  highcharter::hc_mapNavigation(enabled = TRUE)

cntry_weekly_reach %>% select(reach) %>% sum
```


## Country Likes V!

```{r}

cntry_likes <- readr::read_csv("data/cntry_likes.csv") %>% janitor::clean_names()

dscrs4 <- as.list(cntry_likes[1,])

cntry_likes %<>% filter(!is.na(date)) 

cntry <- colnames(cntry_likes)[-1] %>% str_extract("..$") %>% 
  countrycode::countrycode("iso2c", "country.name") 

#cntry[134] <- "Kosovo"

cntry <- c("date", cntry)

colnames(cntry_likes) <- cntry

cntry_likes %<>% 
  gather("cntry", "likes", -date) %>% 
  mutate(likes = as.numeric(likes)) %>% 
  mutate(iso3 = countrycode::countrycode(cntry, "country.name", "iso3c"))

cntry_likes %>% 
  select(iso3, likes) %>% 
  group_by(iso3) %>% 
  summarize(likes = sum(likes, na.rm = T)) %>% 
  hc_world_map(
    iso3 = "iso3", 
    value = "likes"
  ) %>%
  highcharter::hc_colorAxis(stops = stops) %>%
  highcharter::hc_title(
    text = "Total Page Likes (11.384 on January 7th 2018)"
  ) %>% 
  highcharter::hc_subtitle(text = "Based on Data from Omar Saif Ghobash's Facebook page. \t By user country in unique users (Total = 264.755)") %>%
#  highcharter::hc_credits(enabled = TRUE, text = "Based on Data from Omar Saif Ghobash's Facebook page") %>% 
  highcharter::hc_add_theme(highcharter::hc_theme_smpl()) %>% 
  highcharter::hc_mapNavigation(enabled = TRUE)

```

## Country Likes V!

```{r}
cntry_likes <- readr::read_csv("data/cntry_likes.csv") %>% janitor::clean_names()

total_follows <- readr::read_csv("data/total_follows.csv") %>% janitor::clean_names()


dscrs4 <- as.list(cntry_likes[1,])

cntry_likes %<>% filter(!is.na(date)) 

total_follows %<>% filter(!is.na(date)) 


totalikes <- cntry_likes %>% 
  select(-date) %>% 
  mutate_all(funs(as.numeric)) %>% 
  rowSums(., na.rm = T) %>% 
  cbind(cntry_likes %>% select(date), .)

colnames(totalikes) <- c("date", "likes")


total_follows <- total_follows %>% 
  select(-date) %>% 
  mutate_all(funs(as.numeric)) %>% 
  rowSums(., na.rm = T) %>% 
  cbind(total_follows %>% select(date), .)

colnames(total_follows) <- c("date", "follows")

hc_dat <- total_follows %>% 
  left_join(totalikes, by = "date")

highchart() %>% 
  hc_xAxis(categories = hc_dat$date) %>% 
  hc_add_series(name = "Follows", data = hc_dat$follows, type = "area") %>% 
  hc_add_series(name = "Likes", data = hc_dat$likes, type = "area") %>% 
  hc_add_theme(hc_theme_smpl())
  


```

# pages

```{r}
pages <- readr::read_csv("data/pages.csv") %>% janitor::clean_names()

dscrs2 <- as.list(pages[1,])

pages %<>% filter(!is.na(date)) %>% 
  select(-date) %>% 
  mutate_all(funs(as.numeric)) %>% 
  cbind(pages %>% filter(!is.na(date)) %>% select(date), .)





highchart() %>% 
  hc_xAxis(categories = pages$date) %>% 
  hc_add_series(name = "daily_page_stories", data = pages$daily_page_stories) %>% 
  hc_add_series(name = "daily_page_consumptions", data = pages$daily_page_consumptions) %>% 
  hc_add_series(name = "daily_post_engagements", data = pages$daily_post_engagements) %>% 
  hc_add_series(name = "daily_page_engaged_users", data = pages$daily_page_engaged_users) %>% 
  hc_add_series(name = "daily_new_likes", data = pages$daily_new_likes) %>%
  hc_add_series(name = "daily_new_follows", data = pages$daily_new_follows) %>%
  hc_add_series(name = "daily_total_video_views", data = pages$daily_total_video_views) %>%
  hc_add_theme(hc_theme_smpl())
  
```

## Timeseries

```{r}
library(xts)


    
make_xts <- function(variables, date) {
  as.ts(xts(x=variables, order.by = date))
}


x <- cbind(make_xts(pages$daily_total_impressions, pages$date), 
           make_xts(pages$daily_total_reach, pages$date), 
           make_xts(pages$daily_total_consumers, pages$date), 
           make_xts(pages$daily_total_video_views, pages$date))

hchart(as.ts(x)) %>%
  hc_add_theme(hc_theme_smpl())



    #sent_total <- xts(x=x$sent_pool, order.by = x$time)
    
    library(highcharter)
    highchart(type = "stock")  %>%
      #hc_add_series(sent_total, color = "blue") %>% 
      #hc_credits(enabled = TRUE) %>%
      #hc_exporting(enabled = TRUE) 
      hc_add_series(
      make_xts(pages$daily_page_stories, pages$date), type = "area", color = "red"
      ) %>% 
      hc_add_series(
      make_xts(pages$daily_page_consumptions, pages$date), type = "area", color = "green"
      )  
      #hc_exporting(enabled = T) %>%
    
    
    
cumsum(pages$daily_page_stories)

if_else_replace <- function(variables) {
  ifelse(is.na(variables), 0, variables)
}

pages %<>% 
  mutate_if(.predicate = is.numeric, if_else_replace) %>% 
  mutate_if(.predicate = is.numeric, cumsum)

x <- cbind(make_xts(pages$daily_total_impressions, pages$date), 
           make_xts(pages$daily_total_reach, pages$date), 
           make_xts(pages$daily_total_consumers, pages$date), 
           make_xts(pages$daily_total_video_views, pages$date))

hchart(as.ts(x)) %>%
  hc_add_theme(hc_theme_smpl())

```

## gender und age

```{r}

agender_likes <- readr::read_csv("data/agender_likes.csv") %>% janitor::clean_names()

agenders <- colnames(agender_likes)[-1] %>% str_extract(".......$") 

agenders[7] <- "f_f_65"
agenders[14] <- "m_m_65"
agenders[20] <- "u_u_65"

colnames(agender_likes) <- c("date", agenders)

agender_likes %<>% 
  filter(!is.na(date)) %>% 
  select(-u_13_17, -u_25_34, -u_35_44, -u_45_54, -u_55_64, -u_u_65) %>% 
  gather("agender", "likes", -date) 

genders <- agender_likes$agender %>% str_split("_") %>% 
  as.data.frame %>% janitor::clean_names()

agender_likes$gender <- as.character(as_vector(genders[1,]))
agender_likes$age <- paste0(as.character(as_vector(genders[2,])), "-", as.character(as_vector(genders[3,])))



table(agender_likes$age)


library(ggplot2)
agender_likes %>%
  mutate(age = case_when(
    age == "f-65" ~ "65+",
    age == "m-65" ~ "65+",
    TRUE ~ as.character(age)
  )) %>% 
  mutate(likes = as.numeric(likes)) %>% 
  mutate(likes = ifelse(gender == "f", -likes, likes)) %>% 
  mutate(gender = fct_rev(factor(gender))) %>% 
ggplot(aes(x=age, y=likes, fill=gender)) + 
  geom_bar(stat="identity", position="identity", aes(x=age, y=likes, fill=gender)) + 
  geom_bar(stat="identity", position="identity") + 
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight()
  plotly::ggplotly()


```


### Chart B {data-commentary-width=560}

```{r}

numextract <- function(string){ 
  str_extract(string, "\\-*\\d+\\.*\\d*")
} 

total_frequency <- readr::read_csv("data/total_frequency.csv") %>% janitor::clean_names()

describes  <- as.list(total_frequency[1,])

total_frequency %<>% filter(!is.na(date)) %>% 
  select(-date) %>% 
  mutate_all(funs(as.numeric)) %>% 
  cbind(total_frequency %>% filter(!is.na(date)) %>% select(date), .) 

# total_frequency %>% 
#   gather("distrib", "freq", -date) %>% 
#   mutate(distrib = numextract(distrib)) %>% 
#   mutate(distrib = case_when(
#     distrib == "6" ~ "6-10",
#     distrib == "11" ~ "11-20",
#     distrib == "21" ~ "21+",
#     TRUE ~ distrib
#   )) #%>% 
# #  group_by(distrib) %>% 
# #  summarise(freq = sum(freq, na.rm = T))


highchart() %>% 
  hc_chart(type = "area") %>% 
  hc_title(text = "Unique users reached by how many times they saw any page content") %>% 
#  hc_subtitle(text = "Source: Wikipedia.org") %>% 
  hc_xAxis(categories = total_frequency$date,
           tickmarkPlacement = "on",
           title = list(enabled = FALSE)) %>% 
  hc_yAxis(title = list(text = "Percent")) %>% 
  hc_tooltip(pointFormat = "<span style=\"color:{series.color}\">{series.name}</span>:
             <b>{point.percentage:.1f}%</b> ({point.y:,.0f})<br/>",
             shared = TRUE) %>% 
  hc_plotOptions(area = list(
     stacking = "percent",
     lineColor = "black",
     lineWidth = 0.1,
     marker = list(
       lineWidth = 0.1,
       lineColor = "black"
       ))
     ) %>% 
  hc_add_series(name = "1 View", data = total_frequency$daily_total_frequency_distribution_1) %>% 
  hc_add_series(name = "2 Views", data = total_frequency$daily_total_frequency_distribution_2) %>%
  hc_add_series(name = "3 Views", data = total_frequency$daily_total_frequency_distribution_3) %>% 
  hc_add_series(name = "4 Views", data = total_frequency$daily_total_frequency_distribution_4) %>% 
  hc_add_series(name = "5 Views", data = total_frequency$daily_total_frequency_distribution_5) %>%  
  hc_add_series(name = "6-10 Views", data = total_frequency$daily_total_frequency_distribution_6_10) %>% 
  hc_add_series(name = "11-20 Views", data = total_frequency$daily_total_frequency_distribution_11_20) %>% 
  hc_add_series(name = "+21 Views", data = total_frequency$daily_total_frequency_distribution_21) %>% 
  hc_add_theme(hc_theme_smpl())
       

```

### Chart C {data-commentary-width=560}

```{r}
prc_chart <- total_frequency %>% 
  mutate_if(.predicate = is.numeric, .funs = if_else_replace) %>% 
  mutate_if(.predicate = is.numeric, .funs = cumsum) %>% 
  .[nrow(total_frequency),]
#  mutate(distrib = case_when(
#    distrib == "6" ~ "6-10",
#    distrib == "11" ~ "11-20",
#    distrib == "21" ~ "21+",
#    TRUE ~ distrib
#  )) #%>% 
#  group_by(distrib) %>% 
#  summarise(freq = sum(freq, na.rm = T))

highchart() %>%
    hc_xAxis(categories = "%",
             title = "Percentages") %>% 
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_1,
                  name = "1 View") %>%   
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_2,
                  name = "2 Views") %>%  
    hc_add_series(data = prc_chart$aily_total_frequency_distribution_3,
                  name = "3 Views") %>%    
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_4,
                  name = "4 Views") %>% 
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_5,
                  name = "5 Views") %>% 
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_6_10,
                  name = "6-10 Views") %>% 
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_11_20,
                  name = "11-20 Views") %>% 
    hc_add_series(data = prc_chart$daily_total_frequency_distribution_21,
                  name = "+21 Views") %>% 
    hc_chart(type = "bar") %>%
    hc_plotOptions(series = list(stacking = "percent")) %>%
    hc_tooltip(pointFormat = "<span style=\"color:{series.color}\">{series.name}</span>:
             <b>{point.percentage:.1f}%</b> ({point.y:,.0f})<br/>") %>% 
    hc_yAxis(title = list(text = "Percentage")) %>%
#    hc_legend(reversed = TRUE) %>% 
    hc_add_theme(hc_theme_smpl()) %>% 
    hc_size(300, 200)  %>%
    hc_legend(enabled = T, align = "center", verticalAlign = "bottom",
              layout = "horizontal"
 )
```